name: deploy-prod

on:
  release:
    types: [released]

jobs:  
  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: prod
      gcp-project: gcp-blah-blah-prod
      app-engine-url: 'https://google.com'
    secrets:
      SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}
